#!/bin/bash

# Requires running foamLog <log-file> first!!

gnuplot -persist >/dev/null 2>&2 << EOF 
   set logscale y 
   plot "logs/Ux_0" with lines, \
        "logs/Uy_0" with lines, \
        "logs/p_0" with lines,  \
        "logs/k_0" with lines,  \
        "logs/epsilon_0" with lines 
EOF 
